// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';
    systemDictionary = {
        "fritzdect adapter settings": {"de": "fritzdect Adapter Einstellung", "en": "fritzdect adapter setup", "ru": "Настройки fritzdect Драйвера"},
	      "enable DECT200 temp reading": {"de": "DECT200 Temp einlesen", "en": "enable DECT200 temp reading", "ru": "enable DECT200 temp reading"},
	      "enable DECT200 voltage reading": {"de": "DECT200 Spannung einlesen", "en": "enable DECT200 voltage reading", "ru": "enable DECT200 voltage reading"},
	      "on save adapter restarts with new config immediately": {"de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.",
								 	"ru": "Сразу после сохранения настроек драйвер перезапуститься с новыми значениями"}
    };
