/*global systemDictionary:true */
'use strict';

systemDictionary = {
	"Fritzbox IP": {"en": "Fritzbox IP", "de": "Fritzbox IP", "ru": "Fritzbox IP","pt": "Fritzbox IP", "nl": "Fritzbox IP", "fr": "Fritzbox IP", "it": "Fritzbox IP", "es": "Fritzbox IP", "pl": "Fritzbox IP"},
    "Fritzbox Password": {"en": "Fritzbox Password", "de": "Fritzbox Password", "ru": "Пароль Fritzbox",        "pt": "Senha Fritzbox",         "nl": "Fritzbox wachtwoord",    "fr": "Mot de passe Fritzbox",  "it": "Fritzbox Password",      "es": "Contrase�a de Fritzbox", "pl": "Haslo Fritzboksa"},
	"Fritzbox Polling Interval": {"en": "Fritzbox Polling Interval", "de": "Fritzbox Polling Interval", "ru": "Интервал опроса Fritzbox",                       "pt": "Fritzbox Polling Interval",                      "nl": "Fritzbox Polling - interval",                      "fr": "Fritzbox Intervalle d'interrogation",            "it": "Intervallo di polling Fritzbox",                 "es": "Intervalo de interrogaci�n de Fritzbox",         "pl": "Fritzbox Polling Interval"},
	"Fritzbox User": {"en": "Fritzbox User", "de": "Fritzbox User", "ru": "Пользователь Fritzbox",  "pt": "Usu�rio de Fritzbox",    "nl": "Fritzbox - gebruiker",     "fr": "Utilisateur de Fritzbox",                        "it": "Utente Fritzbox",        "es": "Usuario de Fritzbox",    "pl": "Uzytkownik Fritzboksa"},
	"enable DECT200 temp reading": {"en": "enable DECT200 temp reading", "de": "DECT200 Temp einlesen", "ru": "включить чтение DECT200",                        "pt": "habilite a leitura de temperatura DECT200",      "nl": "DECT200 tempelezing inschakelen",                "fr": "activer la lecture de temp�rature DECT200",      "it": "abilita la lettura temporanea DECT200",          "es": "habilitar la lectura de DECT200 temp",           "pl": "wlaczyc odczyt temperatury DECT200"},
	"enable DECT200 voltage reading": {"en": "enable DECT200 voltage reading", "de": "DECT200 Spannung einlesen", "ru": "включить чтение напряжения DECT200",             "pt": "habilite a leitura de tens�o DECT200",           "nl": "schakel DECT200 - spanningswaarde in",             "fr": "activer la lecture de tension DECT200",          "it": "abilitare la lettura della tensione DECT200",    "es": "habilitar la lectura de voltaje DECT200",        "pl": "wlaczyc odczyt napiecia DECT200"},
	"fritzdect adapter settings": {"en": "fritzdect adapter setup", "de": "fritzdect Adapter Einstellung", "ru": "Настройка адаптера fritzdect",                   "pt": "configura��o do adaptador fritzdect",            "nl": "fritzdect adapter instellen",                    "fr": "configuration de l'adaptateur fritzdect",        "it": "impostazione dell'adattatore fritzdect",         "es": "configuraci�n del adaptador de Fritzdect",       "pl": "Konfiguracja adaptera fritzdect"}
};
