/*global systemDictionary:true */
'use strict';

systemDictionary = {
	'fritzdect adapter settings': {
		en: 'Adapter settings for fritzdect',
		de: 'Adaptereinstellungen für fritzdect',
		ru: 'Настройки адаптера для fritzdect',
		pt: 'Configurações do adaptador para fritzdect',
		nl: 'Adapterinstellingen voor fritzdect',
		fr: "Paramètres d'adaptateur pour fritzdect",
		it: "Impostazioni dell'adattatore per fritzdect",
		es: 'Ajustes del adaptador para fritzdect',
		pl: 'Ustawienia adaptera dla fritzdect',
		'zh-cn': 'fritzdect的适配器设置'
	},
	myColor: {
		en: 'myColor',
		de: 'meineColor',
		ru: 'Мой цвет',
		pt: 'minhaCor',
		nl: 'mijnKleur',
		fr: 'maCouleur',
		it: 'mioColore',
		es: 'miColor',
		pl: 'mójKolor',
		'zh-cn': '我的颜色'
	},
	myColor_tooltip: {
		en: 'Description of\nmyColor',
		de: 'Beschreibung von\nmyColor',
		ru: 'Описание\nmyColor',
		pt: 'Descrição de\nmyColor',
		nl: 'Beschrijving van\nmyColor',
		fr: 'Description de\nmyColor',
		it: 'Descrizione di\nmyColor',
		es: 'Descripción de\nmyColor',
		pl: 'Opis\nmyColor',
		'zh-cn': '\nmyColor的描述'
	},
	htmlText: {
		en: 'htmlText',
		de: 'htmlText',
		ru: 'htmlText',
		pt: 'htmlText',
		nl: 'htmlText',
		fr: 'htmlText',
		it: 'htmlText',
		es: 'htmlText',
		pl: 'htmlText',
		'zh-cn': 'htmlText'
	},
	group_extraMyset: {
		en: 'extraMyset',
		de: 'extraMyset',
		ru: 'extraMyset',
		pt: 'extraMyset',
		nl: 'extraMyset',
		fr: 'extraMyset',
		it: 'extraMyset',
		es: 'extraMyset',
		pl: 'extraMyset',
		'zh-cn': 'extraMyset'
	},
	extraAttr: {
		en: 'extraAttr',
		de: 'extraAttr',
		ru: 'extraAttr',
		pt: 'extraAttr',
		nl: 'extraAttr',
		fr: 'extraAttr',
		it: 'extraAttr',
		es: 'extraAttr',
		pl: 'extraAttr',
		'zh-cn': 'extraAttr'
	},
	Instance: {
		en: 'Instance',
		de: 'Instanz',
		ru: 'Инстанция',
		pt: 'Instância',
		nl: 'Instantie',
		fr: 'Instance',
		it: 'Esempio',
		es: 'Instancia',
		pl: 'Instancja',
		'zh-cn': '例'
	},
	'FritzBox Adapter Debugging': {
		en: 'FritzBox Adapter Debugging',
		de: 'FritzBox Adapter Debuggen',
		ru: 'Отладка адаптера FritzBox',
		pt: 'Depuração do adaptador FritzBox',
		nl: 'FritzBox Adapter Debugging',
		fr: "Débogage de l'adaptateur FritzBox",
		it: 'Debug della scheda FritzBox',
		es: 'Depuración del adaptador FritzBox',
		pl: 'Debugowanie FritzBox Adapter',
		'zh-cn': 'FritzBox适配器调试'
	},
	'Fritzbox IP': {
		en: 'Fritzbox IP',
		de: 'Fritzbox IP',
		ru: 'Fritzbox IP',
		pt: 'Fritzbox IP',
		nl: 'Fritzbox IP',
		fr: 'Fritzbox IP',
		it: 'Fritzbox IP',
		es: 'Fritzbox IP',
		pl: 'Fritzbox IP',
		'zh-cn': 'Fritzbox IP'
	},
	'Fritzbox Password': {
		en: 'Fritzbox Password',
		de: 'Fritzbox Password',
		ru: 'Пароль Fritzbox',
		pt: 'Senha Fritzbox',
		nl: 'Fritzbox wachtwoord',
		fr: 'Mot de passe Fritzbox',
		it: 'Fritzbox Password',
		es: 'Contrase�a de Fritzbox',
		pl: 'Haslo Fritzboksa',
		'zh-cn': 'Fritzbox密码'
	},
	'Fritzbox Polling Interval (sek.)': {
		en: 'Fritzbox Polling Interval (sek.)',
		de: 'Fritzbox Abrufintervall (sek.)',
		ru: 'Интервал опроса Fritzbox (сек.)',
		pt: 'Intervalo de Polling do Fritzbox (sek.)',
		nl: 'Fritzbox Polling Interval (sek.)',
		fr: "Fritzbox Intervalle d'interrogation (sek.)",
		it: 'Fritzbox Polling Interval (sek.)',
		es: 'Intervalo de sondeo de Fritzbox (sek)',
		pl: 'Fritzbox Polling Interval (sek.)',
		'zh-cn': 'Fritzbox轮询间隔（sek。）'
	},
	'Fritzbox User': {
		en: 'Fritzbox User',
		de: 'Fritzbox User',
		ru: 'Пользователь Fritzbox',
		pt: 'Usu�rio de Fritzbox',
		nl: 'Fritzbox - gebruiker',
		fr: 'Utilisateur de Fritzbox',
		it: 'Utente Fritzbox',
		es: 'Usuario de Fritzbox',
		pl: 'Uzytkownik Fritzboksa',
		'zh-cn': 'Fritzbox用户'
	},
	'My Devices': {
		en: 'My Devices',
		de: 'Meine Geräte',
		ru: 'Мои устройства',
		pt: 'Meus dispositivos',
		nl: 'Mijn apparaten',
		fr: 'Mes appareils',
		it: 'I miei dispositivi',
		es: 'Mis dispositivos',
		pl: 'Moje urządzenia',
		'zh-cn': '我的设备'
	},
	'My Groups': {
		en: 'My Groups',
		de: 'Meine Gruppen',
		ru: 'Мои группы',
		pt: 'Meus grupos',
		nl: 'Mijn groepen',
		fr: 'Mes groupes',
		it: 'I miei gruppi',
		es: 'Mis grupos',
		pl: 'Moje grupy',
		'zh-cn': '我的团队'
	},
	'must be unchecked (false) if https is used': {
		en: 'must be unchecked (false) if https is used',
		de: 'muss deaktiviert sein (false), wenn https verwendet wird',
		ru: 'должен быть снят (false), если используется https',
		pt: 'deve ser desmarcado (falso) se https for usado',
		nl: 'moet uitgeschakeld zijn (false) als https wordt gebruikt',
		fr: 'doit être décochée (false) si https est utilisé',
		it: 'deve essere deselezionato (falso) se viene utilizzato https',
		es: 'debe estar sin marcar (falso) si se usa https',
		pl: 'musi być odznaczone (false), jeśli używany jest protokół https',
		'zh-cn': '如果使用https，则必须取消选中（false）'
	}
};
